version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            -   ./:/var/www
            -   ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            -   "8876:80"
        depends_on:
            -   app
        container_name: project_nginx

    app:
        dns:
            - 8.8.8.8
            - 8.8.4.4
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            -   ./:/var/www
        container_name: project_app

    postgres:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_DB: BugTrackerDB
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: parol372
        volumes:
            -   pgdata:/var/lib/postgresql/data
        ports:
            -   "5433:5432"
        container_name: project_postgres

volumes:
    pgdata:
